/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * アカウントを登録する
         * @description 登録に成功するとセッション Cookie を返す。
         *     登録と同時にログイン済みになる。
         *
         */
        post: operations["signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログインする
         * @description **識別名の存在有無を漏らさない。** 存在しない識別名とパスワード誤りで
         *     応答が区別できないようにしている（ADR-0006）。
         *
         */
        post: operations["logIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログアウトする
         * @description サーバー側のセッションを削除する。**次のリクエストから即座に効く。**
         *
         */
        post: operations["logOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ログイン中の利用者を取得する */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * プロフィールを更新する
         * @description 表示名と自己紹介を変える（FR-01-03）。
         *
         *     **省略と空文字を区別する。** 項目を送らなければ変えない。
         *     空文字を送ればその項目を消す。自己紹介は消せなければならない。
         *
         *     **アイコンは扱わない。** 画像を置く場所が設計されていない
         *     （オブジェクトストレージの選定が未了。#62）。
         *
         */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/prosody/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 本文を判定する（保存しない）
         * @description 入力中の判定に使う。**何も保存しない。**
         *
         *     破調・読めない語も 200 で返る。判定を求められて判定を返しているため、
         *     エラーではない。投稿できるかは `verdict` で判断する。
         *
         */
        post: operations["checkProsody"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 投稿する
         * @description **判定結果を受け取らない。** サーバー側で必ず再判定する（基本設計 01 §4）。
         *     リクエストに `verdict` を添えても読まない。
         *
         */
        post: operations["createPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 投稿の ID */
                id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        /**
         * 投稿を取得する
         * @description ログインは不要。ログイン済みなら `liked_by_me` が返る。
         *
         *     見えない投稿は 404 とする（削除済み・ブロック関係・フォロワー限定）。
         *     理由を区別しない。区別すると存在を教えてしまう。
         *
         */
        get: operations["getPost"];
        put?: never;
        post?: never;
        /**
         * 投稿を削除する
         * @description 削除できるのは投稿者本人だけ（BR-03）。論理削除であり行は残る。
         */
        delete: operations["deletePost"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}/like": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 投稿の ID */
                id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * いいねする
         * @description **冪等。** すでにいいね済みでも 200 を返し、件数は増えない。
         */
        put: operations["likePost"];
        post?: never;
        /**
         * いいねを取り消す
         * @description **冪等。** いいねしていなくても 200 を返す。
         */
        delete: operations["unlikePost"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 投稿の ID */
                id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 投稿を通報する
         * @description **冪等にしない。** 同じ投稿への2回目は 409 を返す。
         *     黙って成功を返すと「通報が届いた」と誤解するためである。
         *
         */
        post: operations["reportPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timelines/public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 全体タイムラインを取得する
         * @description 公開投稿だけを新しい順に返す。ログインは不要。
         *
         *     ログイン済みなら、ブロック関係にある利用者の投稿が除外され、
         *     `liked_by_me` が返る。
         *
         */
        get: operations["getPublicTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/timelines/home": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * フォロー中タイムラインを取得する
         * @description フォローしている利用者の投稿を新しい順に返す。
         *     フォロー先の `followers` 限定の投稿も含む。
         *
         */
        get: operations["getHomeTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{handle}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 利用者の識別名 */
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        /**
         * プロフィールを取得する
         * @description ログインは不要。ログイン済みなら `following` と `blocking` が返る。
         *
         *     **見えない相手は 404 とする。** 理由を区別しない（BR-10）。
         *     相手にブロックされている・利用停止・退会済み・存在しない識別名の
         *     いずれも同じ応答になる。
         *
         *     自分がブロックした相手は**見える**。`blocking` が真になり、
         *     投稿は0件になる（BR-09）。ブロック中一覧に行かなくても解除できるようにするため。
         *
         */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{handle}/posts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 利用者の識別名 */
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        /**
         * ある利用者の投稿一覧を取得する
         * @description 新しい順に返す。ログインは不要。
         *
         *     **フォロワー限定の投稿は閲覧者で変わる**（FR-02-08）。
         *     本人とフォロワーだけが見られる。それ以外と未ログインには
         *     全体公開の投稿だけを返す。
         *
         *     自分がブロックした相手の投稿は0件になる（BR-09）。
         *
         */
        get: operations["getUserPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{handle}/follow": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 利用者の識別名 */
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * フォローする
         * @description **冪等。** すでにフォロー済みでも 200 を返す。
         *
         *     相手が自分をブロックしている場合は 404 とする。
         *     422 を返すとブロックされた事実が分かり、BR-10 に反するためである。
         *
         */
        put: operations["follow"];
        post?: never;
        /**
         * フォローを外す
         * @description **冪等。** フォローしていなくても 200 を返す。
         */
        delete: operations["unfollow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{handle}/block": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 利用者の識別名 */
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * ブロックする
         * @description **冪等。** すでにブロック済みでも 200 を返す。
         *
         *     ブロックするとフォロー関係が双方向に解除される（BR-08）。
         *
         */
        put: operations["block"];
        post?: never;
        /**
         * ブロックを解除する
         * @description **冪等。** フォロー関係は復活しない。
         */
        delete: operations["unblock"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description エラーの共通形式（基本設計 05 §1）。
         *
         *     **`code` で分岐する。** `message` は文言が変わりうるため、
         *     これで分岐するとクライアントが壊れる。
         *      */
        Error: {
            error: {
                /**
                 * @description 分岐に使う識別子
                 * @example VALIDATION_FAILED
                 * @example PROSODY_HACHO
                 * @example NOT_FOUND
                 */
                code: string;
                /** @description 利用者向けの文言 */
                message: string;
                /** @description 直すために必要な情報。破調なら現在の音数、
                 *     読めない語があるならその語。
                 *      */
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        /** @description 利用者の公開情報。
         *
         *     **メールアドレスとパスワードハッシュを含めない。**
         *     本人向けの応答でも、返す必要がないものは返さない。
         *      */
        User: {
            /** @example yamada */
            handle: string;
            /** @example やまだ */
            display_name: string;
            bio: string;
            avatar_url?: string;
        };
        SignUpRequest: {
            handle: string;
            /** Format: email */
            email: string;
            password: string;
            display_name: string;
        };
        LogInRequest: {
            handle: string;
            password: string;
        };
        CheckRequest: {
            body: string;
        };
        /**
         * @description 判定結果。`teikei` と `kyoyo` だけが投稿できる。
         *
         * @enum {string}
         */
        Verdict: "teikei" | "kyoyo" | "hacho" | "unknown";
        /**
         * @description 判定できなかった理由
         * @enum {string}
         */
        Reason: "TOO_FEW_MORA" | "TOO_MANY_MORA" | "NO_VALID_SPLIT" | "READING_UNAVAILABLE";
        CheckSegment: {
            text: string;
            /** @description カタカナの読み */
            reading: string;
            mora: number;
            /** @description 規定のモーラ数（5 / 7 / 5） */
            expected: number;
            /** @description 規定との差。字余りが正 */
            diff: number;
        };
        CheckResult: {
            verdict: components["schemas"]["Verdict"];
            reading?: string;
            /** @description `unknown` のときは null。読みを確定できていないため */
            total_mora: number | null;
            /** @description 五七五に区切れない場合は null */
            segments: components["schemas"]["CheckSegment"][] | null;
            reason?: components["schemas"]["Reason"];
            /** @description `unknown` のとき、読めなかった語 */
            unreadable?: string[];
        };
        /** @description **項目を省略すると変えない。** 空文字を送るとその項目を消す。
         *      */
        UpdateProfileRequest: {
            display_name?: string;
            bio?: string;
        };
        ProfileUpdated: {
            handle: string;
            display_name: string;
            bio: string;
            avatar_url?: string;
        };
        Profile: {
            handle: string;
            display_name: string;
            bio?: string;
            avatar_url?: string;
            /** Format: date-time */
            created_at: string;
            /** @description **閲覧者から見える投稿の数。** フォロワー限定を含めた総数を返すと、
             *     一覧に出ている件数と合わない。閲覧者によって変わる。
             *      */
            post_count: number;
            following_count: number;
            follower_count: number;
            /** @description 閲覧者がこの利用者をフォローしているか。未ログインなら false */
            following: boolean;
            /** @description 閲覧者がこの利用者をブロックしているか。未ログインなら false。
             *
             *     **ブロックされているかは返さない**（BR-10）。
             *     ブロックされていれば、そもそも 404 になる。
             *      */
            blocking: boolean;
        };
        /** @description **判定結果を含めない。** 含めても読まない（基本設計 01 §4）。
         *      */
        CreatePostRequest: {
            body: string;
            visibility?: components["schemas"]["Visibility"];
        };
        /**
         * @default public
         * @enum {string}
         */
        Visibility: "public" | "followers";
        PostSegment: {
            text: string;
            mora: number;
        };
        PostAuthor: {
            handle: string;
            display_name: string;
            avatar_url?: string;
        };
        Post: {
            /** @description **文字列で返す。** BIGINT を JSON の数値で返すと、
             *     JavaScript の Number（53bit）で精度が落ちる。
             *      */
            id: string;
            /** @description 正規化後の本文 */
            body: string;
            verdict: components["schemas"]["Verdict"];
            segments: components["schemas"]["PostSegment"][];
            visibility: components["schemas"]["Visibility"];
            like_count: number;
            liked_by_me: boolean;
            author: components["schemas"]["PostAuthor"];
            /** Format: date-time */
            created_at: string;
        };
        Timeline: {
            items: components["schemas"]["Post"][];
            /** @description 続きが無ければ null */
            next_cursor: string | null;
        };
        FollowState: {
            following: boolean;
            followers_count: number;
        };
        LikeState: {
            liked: boolean;
            like_count: number;
        };
        BlockState: {
            blocked: boolean;
        };
        /** @enum {string} */
        ReportReason: "spam" | "harassment" | "inappropriate" | "other";
        ReportRequest: {
            reason: components["schemas"]["ReportReason"];
            comment?: string;
        };
        Report: {
            id: string;
            reason: components["schemas"]["ReportReason"];
            /** @enum {string} */
            status: "pending" | "resolved" | "rejected";
            /** Format: date-time */
            created_at: string;
        };
    };
    responses: {
        /** @description 入力の形式が不正 */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 未ログイン、またはセッション切れ */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 識別名またはパスワードが違う */
        InvalidCredentials: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 権限がない */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 見つからない */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 判定エンジンを利用できない（縮退運転） */
        ProsodyUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 判定エンジンが時間内に応答しなかった */
        UpstreamTimeout: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description 投稿の ID */
        PostId: string;
        /** @description 利用者の識別名 */
        Handle: string;
        /** @description この ID より前を取得する。省略すると最新から */
        Cursor: string;
        /** @description 取得件数 */
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpRequest"];
            };
        };
        responses: {
            /** @description 登録できた */
            201: {
                headers: {
                    /** @description セッション Cookie（`HttpOnly` / `SameSite=Lax`） */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            /** @description 識別名またはメールアドレスが使用済み */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogInRequest"];
            };
        };
        responses: {
            /** @description ログインできた */
            200: {
                headers: {
                    /** @description セッション Cookie */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["InvalidCredentials"];
            403: components["responses"]["Forbidden"];
        };
    };
    logOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ログアウトした */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得できた */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description 更新できた */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileUpdated"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    checkProsody: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckRequest"];
            };
        };
        responses: {
            /** @description 判定した */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckResult"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            503: components["responses"]["ProsodyUnavailable"];
            504: components["responses"]["UpstreamTimeout"];
        };
    };
    createPost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePostRequest"];
            };
        };
        responses: {
            /** @description 投稿できた */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            /** @description 五七五になっていない、または読みを確定できない */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            503: components["responses"]["ProsodyUnavailable"];
            504: components["responses"]["UpstreamTimeout"];
        };
    };
    getPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 投稿の ID */
                id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得できた */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Post"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            404: components["responses"]["NotFound"];
        };
    };
    deletePost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 投稿の ID */
                id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除した */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    likePost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 投稿の ID */
                id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description いいねしている状態になった */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikeState"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    unlikePost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 投稿の ID */
                id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description いいねしていない状態になった */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LikeState"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
        };
    };
    reportPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 投稿の ID */
                id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description 通報した */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            /** @description すでに通報済み */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description 自分の投稿は通報できない（BR-07） */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getPublicTimeline: {
        parameters: {
            query?: {
                /** @description この ID より前を取得する。省略すると最新から */
                cursor?: components["parameters"]["Cursor"];
                /** @description 取得件数 */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得できた */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            400: components["responses"]["ValidationFailed"];
        };
    };
    getHomeTimeline: {
        parameters: {
            query?: {
                /** @description この ID より前を取得する。省略すると最新から */
                cursor?: components["parameters"]["Cursor"];
                /** @description 取得件数 */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得できた */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 利用者の識別名 */
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得できた */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            404: components["responses"]["NotFound"];
        };
    };
    getUserPosts: {
        parameters: {
            query?: {
                /** @description この ID より前を取得する。省略すると最新から */
                cursor?: components["parameters"]["Cursor"];
                /** @description 取得件数 */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path: {
                /** @description 利用者の識別名 */
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 取得できた */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Timeline"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            404: components["responses"]["NotFound"];
        };
    };
    follow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 利用者の識別名 */
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description フォローしている状態になった */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowState"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            /** @description 自分自身、またはブロックしている相手 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    unfollow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 利用者の識別名 */
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description フォローしていない状態になった */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FollowState"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            /** @description 自分自身 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    block: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 利用者の識別名 */
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ブロックしている状態になった */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockState"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            /** @description 自分自身はブロックできない（BR-06） */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    unblock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 利用者の識別名 */
                handle: components["parameters"]["Handle"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ブロックしていない状態になった */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockState"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            401: components["responses"]["Unauthenticated"];
            404: components["responses"]["NotFound"];
            /** @description 自分自身 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
